


server:
  port: 8080


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 驱动配置信息
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wasp?useSSL=false
      username: root
      password: PWcsE8ZXVlqe57VhVxtLCu3kWJcJcHNpwxzpd5ntnGi1T6qJivZewHwAPxlBiqtl/OK2PFPrpJ/toDYezXYGXA==
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJSAzen2nhvlvwKvKv7qiw/HYO4bMiBYHYD0mdPVJZekw0u52uCCO+93SgQ198oRDX9H5TU5KVdO7dAkvB/g8rcCAwEAAQ==
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${spring.datasource.druid.public-key}
      # 启用ConfigFilter
      filter:
        config:
          enabled: true
    #token配置
token:
  #公钥
  public-key-path: classpath:ssl/public.pem
  #私钥
  private-key-path: classpath:ssl/private.pem
  #失效时间
  expiration-time-minutes: 60
  #用于验证签名是否合法，验证方必须包含这些内容才验证通过
  audience: wasp

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: cn.iguodong.wasp.web.entity
  type-enums-package: cn.iguodong.wasp.web.entity.enums
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      table-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

# Spring监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    cn.iguodong.wasp.web.mapper: INFO
  config: classpath:log4j2.yml
